// firebaseConfig.js - generated by assistant
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

const firebaseConfig = {
  apiKey: "AIzaSyC8w3EGQXPBdmFUl6J8zbuvpS0GQu9jv0M",
  authDomain: "reba-df34c.firebaseapp.com",
  projectId: "reba-df34c",
  storageBucket: "reba-df34c.appspot.com",
  messagingSenderId: "840686619600",
  appId: "1:840686619600:web:f43324594e3a579a2e87d5",
  measurementId: "G-ZM80BLM06G"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

export { app, auth, db, storage };
